ssl:
  validate_ssl: true

credentials:
  user: 'olivier.beau@me.com'
  password: 'rfcS@5774'

formats:
  datetime_format: '%Y-%m-%d %H:%M:%S'

events:
  pre_heat_start_offset: 3
  pre_heat_end_offset: 0
  ref_start_offset: 5
  ref_end_offset: 2
  morning_event_start: "06:00:00"
  evening_event_start: "16:00:00"
  event_refresh_seconds: 300

mqtt:
  server: 'homeassistant.local'
  port: 1883
  user: 'rhasspy'
  password: 'rhasspy'