ssl:
  validate_ssl: true

credentials:
  user: ''
  password: ''

formats:
  datetime_format: '%Y-%m-%d %H:%M:%S'

events:
  # offset : event_start - offset
  pre_heat_start_offset: 3
  pre_heat_end_offset: 0
  ref_start_offset: 5
  ref_end_offset: 2
  # based on observation, events are always starting at 6am and 4pm
  # we need that to calculate ref periods
  morning_event_start: "06:00:00"
  evening_event_start: "16:00:00"
  # data will be refreshed after 5mn (avoid killing hydro api)
  event_refresh_seconds: 300

mqtt:
  server: ''
  port: 1883
  user: ''
  password: ''
  # mqtt topic will be {base_topic}/{contract_id}/(next|state|reference_period)/#
  base_topic: 'hydroqc'